name: Nana
description: Lifesteal plugin
main: club.minota.nana.Nana
api-version: 1.13
author: Minota <juanpichardo456@icloud.com>
version: 1.0.0
commands:
  toggleend:
    aliases:
      - te
      - togglee
      - toggletheend
      - toggle-end
    description: Toggle The End.
  togglenether:
    aliases:
      - tn
      - togglen
      - togglethenether
      - toggle-nether
    description: Toggle the Nether.
  withdraw:
    aliases:
      - wd
    description: Withdraw one heart from your health bar, giving it to you as an item.
  home:
    aliases:
      - h
    description: Teleports to your pre-set home.
  sethome:
    aliases:
      - sh
    description: Sets your home location.